version: 2.0

jobs:
  build:
    docker:
      - image: l.gcr.io/google/bazel:3.4.1
    steps:
      - checkout
      - run: bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-beta
      - store_artifacts:
          path: bazel-bin/ijwb/ijwb_bazel.zip
